### ISSUE TITLE
[MP2]aoubt early.md in mp2

### ISSUE THREAD

**Issue by aabb15768** [SystemProgrammingatNTU/SP18-issues#13]
請問下列敘述Create empty early.md in mp2 directory before early bird due date.中
early.md的功用是什麼？只要在mp2放一個檔名為early.md的空檔案在mp2 directory就完成這個作業要求了嗎？

**Comment by jerry73204** [comment]
沒錯，這檔案是給評測程式檢查同學是否提交的機制。
