### ISSUE TITLE
[MP2]conflict resolution

### ISSUE THREAD

**Issue by aabb15768** [SystemProgrammingatNTU/SP18-issues#16]
conflict resolution中提到：The create_and_delete.txt file never appears in the filesystem.，那為什麼
(md5)下仍然會有 create_and_delete.txt 以及其md5 ，這樣replay的時候create_and_delete.txt不是就會出現在logical view嗎

**Comment by jerry73204** [comment]
這是把 commit X 和 commit Y 合併成 commit Z 的範例，他的推論是這樣子的

1. 我們會把所有 X 和 Y 裏任何操作都塞到 Z 下面去，因此會同時出現 create create_and_delete.txt 和 delete create_and_delete.txt，一者來自 X，一者來自 Y。
2. 根據合併規則，操作的生效順序是 copy -> creation -> modification -> deletion，因此先 create create_and_delete.txt 才接着 delete create_and_delete.txt，這個 commit 的效果變成是建立又刪除檔案，等同沒有發生。
3. 爲何要列出 MD5，是根據 commit 格式的規則，只要出現在 new_file 和 modified 的項目都必須列出 MD5。
