### ISSUE TITLE
[MP2]關於路徑

### ISSUE THREAD

**Issue by alan0823666** [SystemProgrammingatNTU/SP18-issues#17]
題目敘述中的 /home/resol/repo     /tmp/mp2-resol.sock

這些是相對路徑(MP2底下的tmp, home) , 還是絕對路徑(根目錄底下的home, tmp)

**Comment by jerry73204** [comment]
UNIX 的絕對路徑都是從根目錄起算。

**Comment by alan0823666** [comment]
那我需要在我的程式中，創建這些資料夾嗎？

**Comment by allenhung1025** [comment]
我也有同樣的疑問 
需要在程式裏面創/home/resol/repo這個資料夾嗎

**Comment by jerry73204** [comment]
不需要，評測會先準備好。
