### ISSUE TITLE
[MP2] conflict rule中的最後一個sample

### ISSUE THREAD

**Issue by rayacers** [SystemProgrammingatNTU/SP18-issues#18]
在conflict rule的最後一個sample中，resol create的file被reep刪掉了，那為什麼resol的第二個commit還能modifiy這個file呢？這個file應該已經不存在於檔案系統中了，這樣跟本不會發生modify的情況，commit也不會有這個檔案。不知道我的理解是否有誤，需要大家開釋。

**Comment by aabb15768** [comment]
Operations in any of these cases don’t take effect:
Creation on an existing file
Deletion or "modification on a non-existing file"
Copying from a non-existing file
因為LoserFS是分散式系統，每個peer之間的動作會有一定的延遲（所以才要盡快更新）
當更新速度比延遲還慢，就需要一些規定來規範，如上。
另外其實網站有提到
：For example, Resol creates openme.txt and then modifies it, and Reep deletes it before Resol’s modification. According to our rule, Resol’s modification has no effect.

**Comment by b04401068** [comment]
請問commit後是否應該告知user success or fail? 
(由於modification應該由mv/cp造成，寫入log應該是代表command成功被執行)

如果commit後告知user success，但後來因其他的指令而被ignore，是不是應該告知fail比較合理?

**Comment by jerry73204** [comment]
@rayacers  & @aabb15768 
最後一個 example 的情境是 Resol 建立檔案時，接着 Reep 看到並刪除這個檔案，此時有可能刪除的訊息被延遲，還沒送到 Resol 手上，使得 Resol 使用者可以 modify，就會發生這情況。上述的情形通常會在很短的時間發生 (以網路來說 < 50ms 之類的)。

當然，如果在幾乎無延遲的假設下， resol 會先收到 reep 的刪除訊息，如此一來，之後 resol 的使用者cp 檔案進去，也應該得到 new_file 而不是 modify。

**Comment by jerry73204** [comment]
@b04401068 以下兩種情況討論

1. Resol 還沒被告知檔案已經刪除：我傾向認爲是 success，因爲 resol 先認定檔案存在，因此才有檔案覆寫（modify），而這操作是否成功是以 cp/mv 指令執行當下的情形來認定。

2. Resol 已被告知檔案已經刪除：Resol 認定檔案不存在，接着執行檔案創建，執行結果應爲 success。

**Comment by howard41436** [comment]
請問真的會發生同一個timestamp下有兩個commit的狀況嗎？timestamp精確到0.01秒，即使刻意設計同個時間點讓兩個user做操作，有沒有可能因為延遲或是其他因素(例如有個proccess仍在進行其他動作，因此慢了一點點收到指令)使得本該一樣的timestamp差了一點點？

**Comment by jerry73204** [comment]
timestamp 精確到毫秒，要製造同個時間點的 commit 機會很低。
不過，控制程式時間的技巧是存在的，評測也會評量這項。

**Comment by howard41436** [comment]
Operations in any of these cases don’t take effect.
: Creation on an existing file
因此如果A create了檔案a，B過了幾毫秒後create了檔案a(B的commit中會顯示為new file而非modify，因為訊息被延遲)，B的creation會無效？不是應該蓋掉比較合理嗎

**Comment by jerry73204** [comment]
@howard41436 你的例子裏面 B 可以成功執行 create ，表示還沒看過 A 新增的檔案，因此 A 還是 B 建立檔案兩件事沒有因果關係，我們也只是在讓 B 的新建無效、還是選擇蓋掉 A 的新建之間做選擇。爲了保證每個 peer 合併的 log 都有一樣的結果，才設立這樣的規則。
