### ISSUE TITLE
[MP2] 關於timestamp的問題

### ISSUE THREAD

**Issue by rayacers** [SystemProgrammingatNTU/SP18-issues#2]
1. timestamp在log file裡是什麼格式呢？
2. 如果自行決定commit時機的話，每個人在使用history command的standard output是不是就會不同？
3. 在append一個新commit的時候，timestamp又要從哪裡取得呢？是UNIX系統的時間嗎？

**Comment by jerry73204** [comment]
1. 評測不會開 repo 裏面的檔案，儲存方式可以參考 MP1 或自己定
2.自行決定 commit 的時機是指你可以單個或多個操作 commit 一次， 也請注意 Special notes 的第四點 `Every peer keeps track of others’ logs as soon as possible.`
3. UNIX timestamp

**Comment by howard41436** [comment]
可是單個或多個commit一次就會造成history的輸出不唯一吧？假如一個user連續新增了兩個檔案，中間其他user都沒做事，那麼有可能被算成一次或兩次commit，history的輸出結果就不一樣？

**Comment by jerry73204** [comment]
使用者新增檔案時，所建立的 commit 只新增到其 peer 程式上，因此每個 peer 的 `history` 可以不一樣，不過任何人  `history -a`都必須一致。
