### ISSUE TITLE
[MP2]log file

### ISSUE THREAD

**Issue by andy94077** [SystemProgrammingatNTU/SP18-issues#26]
請問每個peer各自的log要存在哪裡?如果存在各自的repo，那萬一這個peer沒有上線，其他人不就讀不到他的log了嗎?(因為不知道那個peer的repo路徑)。還是我們可以自己決定要存在哪裡?

**Comment by jerry73204** [comment]
同 mp1 ，我會建議把把 log 放在repo 裡面，雖然評測不會檢查這點。

另外，就算不知道 repo 路徑，也應該能透過 socket 傳輸拿到 log，peer 直接存存取他人的 repo 是不允許的。

至於Peer 可能不再，且作業要求知道最新進度 --> 每個 peer 必須記住其他人的最新 log。
