### ISSUE TITLE
[MP2] .sock檔存放位置

### ISSUE THREAD

**Issue by sam880222** [SystemProgrammingatNTU/SP18-issues#28]
請問/tmp/mp2-resol.sock的/tmp是在根目錄下的還是MP2下自己建的?

**Comment by jerry73204** [comment]
程式自己創建，保證不會事先存在。另外，也請確定程式 exit 之後 socket file 要一同移除。

**Comment by sam880222** [comment]
所以要在MP2底下建立tmp目錄嗎？

**Comment by jerry73204** [comment]
`/tmp` 在根目錄下，應總是存在的。
