### ISSUE TITLE
[MP2] 關於socket

### ISSUE THREAD

**Issue by alan0823666** [SystemProgrammingatNTU/SP18-issues#29]
我的想法是 當一個程式要看別人的record的時候 傳一個要求過去目標的socket，然後那個收到要求的人把record傳過來，這個想法有誤嗎？

每個程式都有自己的一個socket，要收訊息從這裡收，然後寫入別人的socket，如果有五個peer，那麼每個peer都往外接4個socket對嗎？

然後如果有兩個以上的程式 同時write到另一個程式的socket，那個socket會不會壞掉（有一個程式的訊息被覆蓋之類的）
如果會的話要怎麼處理

**Comment by jerry73204** [comment]
這是很好的問題，有很多人寄信問過，提出解法之前我們先分析這個問題。

### socket 的行爲
對 socket file descriptor 執行 send() 或 recv() 預設是 blocking call。舉例來說 peer A 執行 send()，這時候接受者 peer B 還沒執行 recv()，這時候 peer A 就會阻塞。另一種情況是， B 先執行 recv()，而 A 還沒執行 send()，也會導致 B 被阻塞。同樣的，A 先送 3 bytes，而 B 卻 recv() 要求 10 bytes，這時候 B 也會阻塞。

### Sender vs. receiver
如果 B 總是預期 A 會先 send()，這時候爲了避免 B 被 recv() 長時間阻塞，我們可以用 `select()` 解決。

### Sender vs. sender
這是同學提到的情況，如果 A 和 B 都是先跑 send()，這時候兩者都會被阻塞，卻等不到對方 recv()，兩方卡死。
對 A 來說，就像 A 抓住了旗子，A 必須跑 recv() 才能把旗子送給對方，這樣 B 拿到旗子才能 send()。這裏的情況是 A 和 B 都各自抓住自己的旗子，卻想拿對方的旗子過來，造成 hold and wait，這時候怎麼辦，有幾種想法。

### 解法一：協定 sender vs receiver
規定 A 自己的旗子被拿走之前，不能拿 B 的旗子，這句話可以翻譯成我們規定 A 必須先 recv()，而 B 第一步是 send()，這樣就可以解套鎖死的問題，不過，這做法使得 A 無法主動送 資料給 B，B 就必須定時 send() 才能讓 A 送資料。

### 解法二：Non-blocking I/O
可以讓傳送方的 send() 轉爲非阻塞、接收方同樣用 `select()`，即使 send() 結果不成功，我們可以檢查 errno 是否爲 EAGAIN 得知是否要再重送。

```c
// sender
#include <errno.h>
ret = fcntl(sender_fd, F_SETFL, O_NONBLOCK); // do it once

ret = send(sender_fd, buffer size);
// then check ret < 0 and errno == EAGAIN

// receiver, add socket fd to read_set
ret = select(&read_set, &write_set, NULL, NULL);
```
