### ISSUE TITLE
[MP2]Peer sockets上下線時間差問題

### ISSUE THREAD

**Issue by KaoShengChieh** [SystemProgrammingatNTU/SP18-issues#30]
假設有三個peers分別是A、B、C
A在某個時間點下線後B上傳了一些commits
這時B、C的history -a會是一樣的
但是B接著下線，之後就再也沒上線
然後A上線了，但無論怎麼操作
A和C的history -a永遠不會一樣(因為A沒有收到B的commit訊息)
這樣要怎麼辦，C要幫忙傳B的資料嗎？
還是評測history -a的時候保證全部peers一定會開啟？

**Comment by jerry73204** [comment]
`history -a` 必須保證所有人結果都要一樣，以你的例子來說，B 已經下線，A 爲了追上進度必須從 C 拿到 B 記錄的快取。

評測允許一種例外：A、B先開啓，操作之後兩者一起關閉，之後再開啓 C，C 無法拿到 A 和 B 的 log，因此 C 可以不包含 A 和 B 以前的 log。
