### ISSUE TITLE
[MP2]about cp and mv

### ISSUE THREAD

**Issue by b04401068** [SystemProgrammingatNTU/SP18-issues#32]
1. cp和mv command有沒有可能兩個檔案皆開頭為@ (都操作repo的內容)

2. 在cp的例子中有一個為: "cp @myfile.txt /tmp/target.txt does similarly."
但judge(final作業)的細項中寫: (update) Repo to local machine transfer is not needed.
是early bird不需用實作Repo to local machine transfer，還是final作業也不用實作?

**Comment by jerry73204** [comment]
1. yes，cp/mv 只偶有 local machine to local machine 不會發生
2. 只有 early bonus 不需要

**Comment by lin9999** [comment]
@jerry73204 可是Grading 第二點的第一小點後面(update)的部分有提到" Repo to local machine transfer is not needed. "所以這個並不是只最後的judge嗎？

**Comment by jerry73204** [comment]
oops，忙中有錯，那段應寫在 early bonus，已經修正上去了，謝謝指出錯誤。
