### ISSUE TITLE
socket 的tutorial 無法使用

### ISSUE THREAD

**Issue by rr999888tw** [SystemProgrammingatNTU/SP18-issues#34]
我的作法是： 先執行server sider 的process，再執行client side + 參數，

例如：
./server & ./client haha
但卻沒看到任何output

**Comment by rr999888tw** [comment]
我自己解決了： 答案是send 的byte 數 最好跟recv 的byte 數一樣，不然有點難handle

**Comment by jerry73204** [comment]
請愛用 `select()` 或 non-blocking I/O。
