### ISSUE TITLE
[MP2]關於commit

### ISSUE THREAD

**Issue by haribo0915** [SystemProgrammingatNTU/SP18-issues#35]
請問:假設resol執行cp /home/resol/first.txt @first.txt, 此時會新增一組commit在resol的log, 那請問first.txt這個檔案應該是跟所有loserFS的檔案進行比較判斷是newfile, copied, modified還是只會跟resol自己repo底下的檔案進行比較?

**Comment by jerry73204** [comment]
Logical view 是合併所有人 log 之後、跑 replay 得來的，因此檔案操作順序肯定是和所有人的 commit 比較，和自己比較沒有意義。
