### ISSUE TITLE
[mp2]commit 的問題 

### ISSUE THREAD

**Issue by allenhung1025** [SystemProgrammingatNTU/SP18-issues#36]
請問如果md5只有存受影響的file的話， commit的時候要怎麼比對目錄下的檔案和目前最新的commit?

**Comment by jerry73204** [comment]
不是很懂你的問題。我們的作業應該不存在要比對 commit 之間目錄檔案的需求，畢竟檔案列表是透過合併 log 計算來的。

**Comment by KaoShengChieh** [comment]
如果你要用MP1的方式實做commit，那你跟當下的logical view比對即可。
