### ISSUE TITLE
[MP2] mv @identical_file @identical_file

### ISSUE THREAD

**Issue by KaoShengChieh** [SystemProgrammingatNTU/SP18-issues#38]
假設identical_file原本是peer_A的檔案，如果peer_B輸入以下的指令
"mv @identical_file @identical_file"，請問要怎麼辦？
1. 按照正常 "mv @source @destination" 的指令寫入log
2. 視為沒有動作
3. 評測保證不會有類似的指令(其他如："cp @identical_file @identical_file")

在 #11 同學有類似的疑問，但這個稍微有點不一樣，
這個指令實際上會將identical這個檔案從A的repo移到B的repo，
雖然logical_view不受這個指令影響，
但助教認為這是否為一個有效的commit，會影響到history的輸出結果

**Comment by jerry73204** [comment]
不需要 commit，站在使用者角度來說，檔案在那個位置是 transparent，這種情況讓他 fail 就行。
