### ISSUE TITLE
[MP2] concurrent問題

### ISSUE THREAD

**Issue by b04401068** [SystemProgrammingatNTU/SP18-issues#40]
1)請問timestamp是process接到user input的那一刻嗎?但是程式可以自行決定commit的時間，如果接收到兩個以上的input，就無法決定commit的timestamp。還是timestamp是update log的那一刻?

2)若history -a和另一個peer的command同時發生
請問history -a有需要列出另外一個peer的commit嗎?
之前都是peer對file的command同時發生進行resolution的問題，沒有list和history。

**Comment by jerry73204** [comment]
1) 作業沒寫明這點，評測只會看你的 timestamp 的順序是否正確
2) 如果你是說兩者在同個 wall clock time 同時發生，history -a 拿不到隔壁的新 commit 是合理的，作業只有要求 0.5 秒。
