### ISSUE TITLE
[MP2]file creation and modification

### ISSUE THREAD

**Issue by allenhung1025** [SystemProgrammingatNTU/SP18-issues#43]
為什麼md5只需要計算file creation 和 modification?
MD5 digest is calculated only for file creation and modification, and extra (timestamp) in milliseconds is provided

**Comment by jerry73204** [comment]
計算複製或刪除的項目沒有意義，這兩項操作不需要知道內容。
如果你是說爲何不像 mp1 計算 "所有的檔案"？我們很難保證同個 wall clock time 兩個 peer 保證看到同一份檔案清單，要計算所有檔案的 MD5 會增加實作的難度。
