### ISSUE TITLE
[MP2]cross-peer mv問題

### ISSUE THREAD

**Issue by andy94077** [SystemProgrammingatNTU/SP18-issues#44]
假設現在有3個peer p1, p2, p3，p1持有a檔案，現在3個peer都上線，p2跟p3同時執行`mv @a @b`，我現在的做法是每次mv時peer都會問其他上線的peer有沒有持有該檔案，若有則開始mv。但這樣會出現下列的問題:
#### 可能的情況一
1. p1收到p2的詢問，開始傳送a給p2，傳完之後刪除a
2. p2收到p3的詢問，開始傳送a給p3，傳完之後刪除a
結果: p2: success, p3: success
#### 可能的情況二
1. p2收到p3的詢問，但p2沒有檔案
2. p1收到p2的詢問，開始傳送a給p2，傳完之後刪除a
3. p1收到p3的詢問，但p1已經沒有檔案了
結果: p2: success, p3: failed

這樣會造成輸出結果不一致，但我又想不到還有什麼方法能mv了，請問助教到底該怎麼做呢?

**Comment by jerry73204** [comment]
站在 p3 的角度來說，它的問題就是不能確定 (1)查詢檔案清單 ->  (2) 執行複製 兩個操作之間，其他的 peer 有沒有做事，畢竟 (2) 依賴 (1) 的結果，但 (1) -> (2) 不是 atomic，所以無論結果是 success 或 fail 都可以接受。
