### ISSUE TITLE
[MP2]檔名

### ISSUE THREAD

**Issue by jimmycsie** [SystemProgrammingatNTU/SP18-issues#46]
1. 請問所有檔案都是 .txt 嗎？
2. 為什麼例子中 resol 的 commit 2 同時有 new_file, deleted 。 這應該不可能同時發生
3. 當 cp 從 local machine 到 LoserFS 是相同檔案(相同檔名，相同內容) ，需要有 log 紀錄嗎？

**Comment by jerry73204** [comment]
1. nope
2. 這是舉例，在我們作業很少有這情況，除非你選擇用 new_file + deleted 來實作 mv 指令
3. 還是要做，以自己 peer 來說雖然不影響語意，但是如果同時間，有其他 peer 也有對這個檔案操作的話，就會有時間先後的差別。

**Comment by b04401068** [comment]
請問第三項是屬於copied還是modified? (假設此時間僅有此操作?)
MP1好像提到copied是新增的檔案而且檔案內容與LoserFS其中一個檔案相同，
modified要是同樣檔名，但是內容不同。
此情況皆不符合

**Comment by jerry73204** [comment]
這算是作業沒定義的部分，爲了避免爭議，評測不會有這個情形。
