### ISSUE TITLE
[MP2] mp2-judge 測資一 問題

### ISSUE THREAD

**Issue by HcwXd** [SystemProgrammingatNTU/SP18-issues#47]
助教好，想請問關於 mp2-judge 測資一 simple_history_list_test，我的 stdin / stdout 如下
```
stdin: b'history\n' 
stdout: b'\n'
```
Error 給的是
```
'simple_history_list_test': 'Expect "# commit N" after blank lines or at beginning, but get "b\'\\n\'": [b\'\\n\']'
```
因為 config 的 repo 是空目錄，在沒有 `cp` 或是 `mv` 的情況下，我預期應該不會有任何先前的 commit。而就算有先前的 commit，在先前的 issue 中助教有提到「不會看實際存 log 的位置」，因此我應該沒辦法讀取先前的 commit，故我最後的 output 預期是空白。

但 error 告訴我應該要有 commit 的紀錄，想問關於這些紀錄是從何而來，是有先做 `cp` 或 `mv` 嗎？或是我是否有誤解測資的地方，謝謝助教。

**Comment by jerry73204** [comment]
這錯誤訊息的意思不是需要你生 commit，而是 parser 在解你的 history 輸出時，和預期格式不同而發生的錯誤。
評測會預期第一行是 `# commit N` 的格式，因此你印空換行就會出現這個錯誤，你就不要印任何字即可。
