### ISSUE TITLE
[MP2] judge 測資

### ISSUE THREAD

**Issue by jimmycsie** [SystemProgrammingatNTU/SP18-issues#48]
助教你好
我使用測資得到這個 error：'simple_history_list_test': ConnectionResetError('Connection lost')
因為我不熟悉 socket 上網查也看不懂，可以請助教解釋一下可能發生的問題嗎？
第二個問題是我算出來的md5不一樣，不知道mp2-judge中有沒有多個peer同時修改檔案？(因為上面寫是simple test，我在想simple test應該沒有同時修改的測資吧？)

**Comment by jerry73204** [comment]
1. 這通常是你的程式中途不預期地結束，導致評測程式寫入使用者命令時出錯。
2. 不會有你說的情況，試着在評測加上 `--keep-tmp-files` 選項，評測後會留下所有檔案，依據評測記錄的檔案路徑去找到檔案後，你手工驗算 md5 看看。

**Comment by jimmycsie** [comment]
第二點我還是有一些疑惑，我在MP1算出來的md5是正確的(沒有被扣分)，那為什麼這次作業我的md5會算錯，是不是因為檔案是 .bin的關係？因為我打開bin是亂碼所以我用程式讀檔去算，的確算出來評測程式指出的錯誤md5，請問我要如何修改？

這是我用unix方式讀檔，得到test後算出md5
string test;
char buffer[4096];
int read_cnt;
while( (read_cnt = read(fd,buffer,4095)) ){
        buffer[read_cnt]='\0';
        test+=buffer;
}


謝謝

**Comment by jerry73204** [comment]
這行是多餘的 `buffer[read_cnt]='\0';` ，我猜測你程式假定檔案是文字檔，不過計算 MD5 不見得只能在文字檔上實現。
評測的檔案都是隨機生成，都不會是文字格式。
