### ISSUE TITLE
[MP2]關於judge和評測方式

### ISSUE THREAD

**Issue by wayne1204** [SystemProgrammingatNTU/SP18-issues#50]
助教你好
若judge的測資都通過可獲得4.5分
是否就代表能在mp2至少能拿到4.5分?
請問評測的方式也是使用類似這樣的judge程式嗎?
還有評測的環境是什麼
謝謝

**Comment by jerry73204** [comment]
> 是否就代表能在mp2至少能拿到4.5分?

會包含小測資，所以 yes

> 還有評測的環境是什麼

工作站
