### ISSUE TITLE
[mp2-review] b04401068

### ISSUE THREAD

**Issue by b04401068** [SystemProgrammingatNTU/SP18-issues#51]
1. simple_history_list_test
我在工作站上測，不論是在事前釋出的judge或是現在pull的judge
第一個simple_history_list_test都是可以跑的情形，不知道為什麼一開始被kill掉了?
(在工作站上測a.bin的確可以被複製....而且MD5有值，沒有被truncate)

**Comment by b04401068** [comment]
![image](https://user-images.githubusercontent.com/28797797/50167010-215d1d80-0323-11e9-89cc-df0c9806f8f7.png)
此為剛剛在工作站測試的截圖

**Comment by KaoShengChieh** [comment]
同學的問題是不是跟我 #53 一樣QQ

**Comment by jerry73204** [comment]
很高的機會是工作站過載導致的，已經將重測結果送到你的 repo。
另外，因爲你的 rm 有輸出文字，你的分數會是 11.25 - 0.75 = 10.5 分。
