### ISSUE TITLE
[mp2-review] b06705057

### ISSUE THREAD

**Issue by jimmycsie** [SystemProgrammingatNTU/SP18-issues#52]
1. 請問一下是不是只會批改12/11前上傳的程式，我的問題是當沒有任何peer時我程式會當掉，因此我的simple_history_list_test，simple_local_repo_test 是fail的，但是我在截止後幾分鐘有上傳修改這個bug，因為這個小問題導致6分都沒有覺得很痛心，我不是故意拖到期限截止才上傳的，我很早就開始寫了，到最後也一直debug，但是成績非常低，希望助教可以給一些補教機會，像是程式會被繼續批改個幾天但是成績會打折，謝謝助教!!

2. 請問 Receive early EOF in stdout 是甚麼意思?

**Comment by KaoShengChieh** [comment]
幫忙回答第2點:
如果你的程式裡面有類似
> ret = function(parameter);
> if (ret < 0) {
>     perror("function");
>     exit(EXIT_FAILURE);
> }

ret這時又小於0的話
就會出現Receive early EOF in stdout

**Comment by jerry73204** [comment]
麻煩請收信箱，謝謝。
