### ISSUE TITLE
[mp2-review] B06902117

### ISSUE THREAD

**Issue by KaoShengChieh** [SystemProgrammingatNTU/SP18-issues#53]
這是我的'simple_history_list_test'發生錯誤的區段
[INFO]	stdin: b'cp /tmp2/r06922148/TA2018/assignment/mp2/mp2-judge/judge_tmp/tmpc80f_6dw/first.bin @a.bin\n'
[INFO]	stdout: b'success\n'
[INFO]	stdin: b'history\n'
[INFO]	stdout: b'# commit 1\n'
[INFO]	stdout: b'[new_file]\n'
[INFO]	stdout: b'a.bin\n'
[INFO]	stdout: b'[modified]\n'
[INFO]	stdout: b'[copied]\n'
[INFO]	stdout: b'[deleted]\n'
[DEBUG]	Kill peer "B06902117-resol" process

這是我的錯誤訊息
'simple_history_list_test': "Truncated history output: [b'# commit 1\\n', b'[new_file]\\n', b'a.bin\\n', b'[modified]\\n', b'[copied]\\n', b'[deleted]\\n']"
看起來是因為我的程式沒有把MD5和timestamp印出來導致錯誤

但是我評測其他題的history完全沒有這個問題
我之前用範例評測也是正常的
剛剛測試也完全是正常的

請問這個評測有什麼特別的地方嗎
有沒有可能是history還沒印完系統就開始比對

可以的話，希望能針對這一小題再評測一次

**Comment by jerry73204** [comment]
可能是當時工作站過載導致錯誤，重測結果送到你的 repo。
