### ISSUE TITLE
[mp2-review] b04703078

### ISSUE THREAD

**Issue by HcwXd** [SystemProgrammingatNTU/SP18-issues#55]
1. simple_history_list_test
同 #51 #53 ，工作站上測試該項可以通過拿到 3 分，但在 judge_log 中因為 truncate 被 kill。

2. simple_restart_test
同 #54 ，在 judge_log 裡面沒有看到這份測資的評測紀錄。

謝謝助教！

**Comment by jerry73204** [comment]
已經重測，請看 repo 下面的記錄。
