### ISSUE TITLE
[mp2-review] <B04902129>

### ISSUE THREAD

**Issue by james88878** [SystemProgrammingatNTU/SP18-issues#56]
助教您好, 
在 Deadline 前所提交的代碼，使用 Early bird bonus 每個項目都有成功, 並沒有回傳錯誤訊息, 在看到信件後發現分數落差許多, 所以拿最新版本的評測重新跑過一次, 測試的流程及結果似乎跟之前的有些不同, 希望能夠重新進行評測，謝謝助教。

![messageimage_1545238566770](https://user-images.githubusercontent.com/43361543/50237683-7b7be280-03f8-11e9-81c3-e9708b21d8d0.jpg)

**Comment by jerry73204** [comment]
在我這裏得到的評測看來程式的 socket file 的位置不正確，因此評測判定啓動失敗而失分。
另外記錄傳到你的 repo 了
