### ISSUE TITLE
[mp2-review] <B05203047>

### ISSUE THREAD

**Issue by iceage1001** [SystemProgrammingatNTU/SP18-issues#57]
Early bird bonus 有過但評測沒過 
在工作站上跑評測一直沒成功 
照著spec的測資沒有問題 
請助教review 謝謝助教

**Comment by jerry73204** [comment]
程式有幾個小問題
1. MD5 有機會算錯
2. rm 有一定機率會失敗

重新評測的結果送到 repo 了請參考看看。

**Comment by iceage1001** [comment]
助教好:

    我發現評測的peer可以是空的，然而我的程式做了一個assert確保至少有一個peer，

因此導致程式中斷進而造成測試未過，參照了一下spec好像沒有特別註明peer可以為空?

這似乎正是Early bird bonus過了評測卻沒過的原因


________________________________
寄件者: jerry73204 <notifications@github.com>
寄件日期: 2018年12月20日 下午 04:19:59
收件者: SystemProgrammingatNTU/SP18-issues
副本: iceage1001; Author
主旨: Re: [SystemProgrammingatNTU/SP18-issues] [mp2-review] <B05203047> (#57)


程式有幾個小問題

  1.  MD5 有機會算錯
  2.  rm 有一定機率會失敗

重新評測的結果送到 repo 了請參考看看。

**Comment by iceage1001** [comment]
另外early bird bonus的時候提到，即使檔案系統為空也要印出一行(MD5) ?

從log判斷程式的錯誤有點棘手，可否提供測資與測試流程?

希望能盡早釐清產生error的原因    謝謝助教

________________________________
寄件者: 徐衍新 <b05203047@ntu.edu.tw>
寄件日期: 2018年12月21日 下午 07:58:28
收件者: SystemProgrammingatNTU/SP18-issues; SystemProgrammingatNTU/SP18-issues
副本: iceage1001; Author
主旨: RE: [SystemProgrammingatNTU/SP18-issues] [mp2-review] <B05203047> (#57)


助教好:

    我發現評測的peer可以是空的，然而我的程式做了一個assert確保至少有一個peer，

因此導致程式中斷進而造成測試未過，參照了一下spec好像沒有特別註明peer可以為空?

這似乎正是Early bird bonus過了評測卻沒過的原因


________________________________
寄件者: jerry73204 <notifications@github.com>
寄件日期: 2018年12月20日 下午 04:19:59
收件者: SystemProgrammingatNTU/SP18-issues
副本: iceage1001; Author
主旨: Re: [SystemProgrammingatNTU/SP18-issues] [mp2-review] <B05203047> (#57)


程式有幾個小問題

  1.  MD5 有機會算錯
  2.  rm 有一定機率會失敗

重新評測的結果送到 repo 了請參考看看。

**Comment by jerry73204** [comment]
> 從log判斷程式的錯誤有點棘手，可否提供測資與測試流程?

記錄檔有 stdin、stdout 欄位，會記載所的輸入輸出，上面就有有所有的測試流程。
