### ISSUE TITLE
[MP3]Judge #7

### ISSUE THREAD

**Issue by wangyenjen** [SystemProgrammingatNTU/SP18-issues#61]
目前simple judge(judge.py)中的 Judge #7部分是不是有誤，Judge會要求：「1. csie_box_client(編譯出來的可執行檔)必須被刪除、2. client directory要保留，只要刪除清空裡面的內容即可。」 與spec有些不符合。

**Comment by HobeXD** [comment]
這邊我寫錯了 186行應該為
if os.path.exists(client_dir) and len(os.listdir(client_dir)) != 0:

如果 client directory 存在且不為空則為錯誤。
