### ISSUE TITLE
［MP3]

### ISSUE THREAD

**Issue by b04401068** [SystemProgrammingatNTU/SP18-issues#62]
1. Directory 的creation可以透過command line的mv產生嗎？還是只會有mkdir?
(同理，file 會透過mv 產生嗎？）
2. 若server產生一個Symlink的檔案，可否client為一個hardlink file, 但內容相同
3. 當client和server同時在線，server下線後，client是否需要把directory的內容清空？

**Comment by HobeXD** [comment]
1. 只會使用 mkdir
2. 不可
3. 不用，需等待 server 重新上線。
