### ISSUE TITLE
[MP2]關於每個user的權限

### ISSUE THREAD

**Issue by howard41436** [SystemProgrammingatNTU/SP18-issues#9]
請問A和B兩個process在互相溝通時，A若知道B的repo位置，A有讀取那個repo及其中的檔案的read權限嗎？也就是說如果A要看B的repo裡面的檔案，需要將資料通通透過socket傳送嗎還是只要B將自己repo的位置透過socket傳給A，A就能自己讀取那裡面的檔案？

**Comment by jerry73204** [comment]
peer 之間只能透過 socket 傳輸，因此沒有這類的問題。這部分已經更新到 spec 上，感謝提醒。
